DjangoBookMakers/SkillBridge

accounts/views.py
templates/base.html

로그인/회원가입 페이지에서 네비게이션 버튼 중복 제거
회원가입 후 자동 로그인 비활성화
https://github.com/DjangoBookMakers/SkillBridge/issues/6

🛠️ 로그인/회원가입 UI 및 인증 흐름 개선

---

courses/management/commands/create_sample_course.py
courses/templates/courses/course_list.html
courses/views.py

메인화면에서 `인기 과정`도 보여주도록 정렬했습니다.
https://github.com/DjangoBookMakers/SkillBridge/issues/14 중 전체과정리스트 화면에서 `인기 과정`

✨ FEAT: 메인화면 과정 인기순 정렬

---

templates/base.html
templates/footer.html
templates/home_intro.html
templates/navbar.html

#16 base.html이 너무 길지 않도록, 여러 파일로 분할하는 내용입니다.

♻️  REFACTOR: base.html 파일 분할

---

courses/templates/courses/course_detail.html

🚧 TEMP: course_detail.html에 TODO 내용 주석 표기

---

config/urls.py
templates/navbar.html

🐛 FIX: 메인 로고 클릭시 메인 과정 목록 화면으로 이동

---

config/settings.py
learning/admin.py
learning/apps.py
learning/models.py
learning/tests.py
learning/urls.py
learning/views.py

학습 진행 관련 기능 담당
- 학습 진행 상황 추적
- 동영상 강의 시청 기록 관리
- 미션(쪽지시험) 제출 및 채점
- 중간고사/기말고사 프로젝트 제출
- 수강생 대시보드(학습 진행 상황, 수료 상태 등)
- 수료증 발급 기능
- 과정 수료 조건 확인 및 처리

✨ FEAT: learning 앱 추가

---

accounts/forms.py
accounts/templates/accounts/profile.html
accounts/templates/accounts/profile_edit.html
accounts/urls.py
accounts/views.py
templates/navbar.html

- 프로필 이미지 표시
- 사용자 이름 표시	
- 기본 정보 표시 
- 프로필 수정 기능 구현
- 개인 정보 수정 폼
#34

✨ Feat: 사용자 정보 및 관리 화면 구현

---

accounts/forms.py
accounts/templates/accounts/change_password.html
accounts/templates/accounts/profile.html
accounts/urls.py
accounts/views.py

✨ feat: 비밀번호 변경 기능 구현

---

courses/views.py

✨ FEAT: 과정상세화면에서 과정 수강 중인 경우 이어서 학습하기 기능 구현

---

courses/templates/courses/course_detail/reviews.html
courses/urls.py
courses/views.py

✨ FEAT: 수강평 수정 및 삭제 기능 추가

---

accounts/templates/accounts/login.html
accounts/templates/accounts/profile.html
courses/templates/courses/course_detail/reviews.html
learning/templates/learning/mission.html
learning/templates/learning/video_lecture.html
templates/navbar.html

♻️ REFACTOR: 일부 템플릿 파일의 JS 코드 리팩토링

---

admin_portal/templates/admin_portal/dashboard_components/project_table.html
admin_portal/templates/admin_portal/evaluate_project.html
admin_portal/templates/admin_portal/pending_projects.html
admin_portal/templates/admin_portal/project_detail.html
admin_portal/urls.py
admin_portal/views.py
learning/templates/learning/submit_project.html

✨ FEAT: 어드민 대시보드의 프로젝트제출 조회 및 평가 기능 구현

---

admin_portal/templates/admin_portal/dashboard.html
admin_portal/templates/admin_portal/dashboard_components/stats_card.html
admin_portal/views.py

#59 
관리자 대시보드에서 동영상 조회 수를 표시합니다.

✨ FEAT: 관리자 대시보드 동영상 조회 수 표시

---

admin_portal/templates/admin_portal/course_management/course_create.html
admin_portal/templates/admin_portal/course_management/course_detail.html
admin_portal/templates/admin_portal/course_management/course_list.html
admin_portal/templates/admin_portal/course_management/lecture_create.html
admin_portal/templates/admin_portal/course_management/lecture_detail.html
admin_portal/templates/admin_portal/course_management/lecture_list.html
admin_portal/templates/admin_portal/course_management/subject_create.html
admin_portal/templates/admin_portal/course_management/subject_detail.html
admin_portal/templates/admin_portal/course_management/subject_list.html
admin_portal/templates/admin_portal/dashboard.html
admin_portal/urls.py
admin_portal/views.py
config/settings.py

- 대시보드에 과정 목록 버튼 추가
- 과정 관리 URL 라우팅 설정
- 과정 관리 뷰 함수 구현
- 관련 템플릿 추가

✨ 관리자 대시보드 과정 관리 기능 구현

---

admin_portal/templates/admin_portal/dashboard.html
admin_portal/templates/admin_portal/user_learning_records.html
admin_portal/urls.py
admin_portal/views.py

✨ FEAT: 관리자 대시보드에 사용자 학습 기록 기능 구현

---

pdm.lock
pyproject.toml
requirements.txt

➖ CHORE: djangorestframework 및 requirements.txt 제거

---

accounts/apps.py
accounts/forms.py
accounts/models.py
accounts/signals.py
accounts/urls.py
accounts/views.py
admin_portal/views.py

os.path 대신 pathlib 사용
accounts 앱에 black formatter 적용

Fix pathlib black

---

templates/base.html

🐛 Fix: 푸터가 페이지 하단에 고정되도록 flex 레이아웃 적용

---

admin_portal/templates/admin_portal/dashboard.html
admin_portal/templates/admin_portal/payments/payment_detail.html
admin_portal/templates/admin_portal/payments/payment_list.html
admin_portal/urls.py
admin_portal/views.py

✨ FEAT: 관리자 대시보드 결제 내역 관리 기능 추가

---

admin_portal/templates/admin_portal/dashboard.html

🐛 FIX: 관리자 대시보드 버튼 텍스트 수정

---

admin_portal/templates/admin_portal/dashboard.html
admin_portal/templates/admin_portal/payments/payment_list.html
admin_portal/views.py

- 관리자 대시보드에서 매출 정보 값 출력
- 화폐 단위 출력시 콤마 적용

✨ FEAT: 관리자 대시보드에서 매출 정보 값 출력

---

courses/templates/courses/course_detail/header.html
courses/views.py

💄 FEAT: 과정상세화면에서 장바구니에 담긴 과정이면 보여주기

---

accounts/templates/accounts/profile.html
accounts/views.py
payments/templates/payments/payment_history.html

✨ FEAT: 프로필 화면과 구매 내역 화면 간 이동 기능 구현

---

courses/templates/courses/course_detail/curriculum.html
courses/views.py

과정상세화면에 대한 UX 강화 작업입니다.
작업 내용은 커밋 제목 그대로이고요.
#51

Fix admin dashboard UI

---

admin_portal/templates/admin_portal/dashboard.html
admin_portal/templates/admin_portal/manage_enrollment.html
admin_portal/urls.py
admin_portal/views.py

✨ FEAT: 관리자 대시보드에서 수강생의 과정 등록 및 취소 기능 구현

---

config/settings/__init__.py
config/settings/base.py
config/settings/dev.py
config/settings/prod.py

🔧 CHORE: settings.py 파일 분할 및 settings 디렉터리 생성

---

accounts/views.py
admin_portal/models.py
admin_portal/views.py
courses/views.py
learning/views.py
payments/payment_client.py
payments/views.py

🔊 로거 설정 및 로그 메시지 추가

---

admin_portal/templates/admin_portal/course_management/course_create.html
admin_portal/templates/admin_portal/course_management/course_detail.html
admin_portal/views.py
courses/templates/courses/course_list.html

- 과정 난이도 라벨 정렬 및 레이아웃 수정
- 텍스트 줄바꿈 방지 및 정렬 일관성 개선
- 과정명 아래 짧은설명 표시 구현
- 가격에 콤마 추가
- 어드민 페이지 과정 생성/상세 페이지 마이너 UI 조정

✨ Feat: 과정 목록 UI 개선

---

learning/apps.py
learning/signals.py
learning/views.py

강의시청/미션통과/프로젝트통과시 enrollment 상태를 완료로 변경할지 체크
https://github.com/DjangoBookMakers/SkillBridge/pull/111를 revert하고 위 방법으로 교체
#110

🐛 FIX: 강의시청/미션통과/프로젝트통과시 enrollment 상태를 완료로 변경할지 체크

---

admin_portal/mixins.py
admin_portal/urls.py
admin_portal/views.py
learning/templates/learning/project_detail.html

♻️ REFACTOR: admin_portal 앱에 CBV 적용

---

accounts/forms.py
accounts/templates/accounts/change_password.html
accounts/templates/accounts/signup.html

- accounts/forms.py에서 불필요한 스타일 속성 제거
- change_password.html에 필드 스타일 적용
- signup.html에 필드 스타일 적용
- 관심사 분리 원칙에 따라 프레젠테이션 로직을 템플릿으로 이동

🎨 CHORE: 폼에서 CSS 스타일 코드를 템플릿으로 이동

---

admin_portal/templates/admin_portal/course_management/subject_list.html
admin_portal/views.py

- 중간고사와 기말고사 과목의 강의 수를 -로 표시
- 중간고사와 기말고사 과목의 강의 관리부분 제거
- 과목 관리 뷰의 강의 수 로직 업데이트

📚 FEAT: 과목 유형에 따른 강의 수 및 관리 표시 개선

---

courses/urls.py
courses/views.py
learning/urls.py
learning/views.py
payments/urls.py
payments/views.py

#115 
courses, learning, payments 앱에 적용

Feature cbv

---

admin_portal/templates/admin_portal/course_management/lecture_list.html
admin_portal/templates/admin_portal/dashboard.html
admin_portal/templates/admin_portal/qna_detail.html
admin_portal/templates/admin_portal/qna_management.html
admin_portal/urls.py
admin_portal/views_qna.py
courses/urls.py
courses/views.py
learning/templates/learning/video_lecture.html
learning/views.py

#125 
강의의 질문에 대한 답변 생성/추가/삭제 기능 구현입니다.
아래 2가지 위치에서 수행 가능합니다.
- 관리자 대시보드
- 강의 화면에서 직접

Feature video lecture qna

---

accounts/signals.py

마이그레이션 후 관리자 계정 자동 생성하는 내용입니다.
#128

🔨 CHORE: accounts 앱 migration시 기본 관리자 계정 생성

---

.github/workflows/deploy.yml
Dockerfile
docker-compose.yml

🐛 FIX: 배포 설정 파일 문법 오류 및 migration 누락 수정

---

Dockerfile
docker-compose.yml

🐛 FIX: python 명령 및 gunicorn을 pdm을 통해 실행하도록 수정

---

pdm.lock
pyproject.toml

#134 
배포환경에서 postgres 사용을 위한 psycopg2 라이브러리 설치

➕ CHORE: postgres 사용을 위한 psycopg2 라이브러리 설치

---

pdm.lock
pyproject.toml

➕ CHORE: postgres 사용을 위한 psycopg2-binary 라이브러리 설치

---

.github/workflows/deploy.yml

🐛 FIX: 배포 스크립트에 잘못 기재된 데이터베이스 환경변수 수정

---

courses/management/commands/create_datascience_nanodegree.py
courses/management/commands/create_frontend_nanodegree.py

🐛 FIX: 샘플 과정의 난이도 조절

---

courses/templates/courses/course_list.html

💄 STYLE: 메인 화면의 과정 카드의 버튼 위치를 하단에 고정

---

courses/management/commands/create_datascience_nanodegree.py
courses/management/commands/create_frontend_nanodegree.py
courses/templates/courses/course_list.html
courses/views.py
templates/base.html

main 브랜치 업데이트

---

nginx/nginx.conf

🐛 FIX: nginx.conf의 server_name 수정

---

admin_portal/templates/admin_portal/dashboard.html
admin_portal/views.py

✨ FEAT: 관리자 대시보드에 매출 통계 그래프 추가

---

README.md

📝 DOCS: README에 API 명세 및 디렉터리 구조 작성

---

README.md
docs/deployment-architecture.svg
docs/project-architecture.svg

📝 DOCS: README에 Django 프로젝트 아키텍처 설명 추가

---

admin_portal/templates/admin_portal/payments/payment_list.html
admin_portal/views.py

🐛 FIX: 관리자 대시보드 결제 내역의 완료된 거래 값이 안 나오는 문제 해결
